CREATE TABLE player_match_history (
        element_id INTEGER,
        round INTEGER,
        fixture_id INTEGER,
        opponent_team INTEGER,
        was_home INTEGER,
        total_points INTEGER,
        minutes INTEGER,
        goals_scored INTEGER,
        assists INTEGER,
        clean_sheets INTEGER,
        goals_conceded INTEGER,
        expected_goals TEXT,
        expected_assists TEXT,
        expected_goal_involvements TEXT,
        expected_goals_conceded TEXT,
        influence TEXT,
        creativity TEXT,
        threat TEXT,
        ict_index TEXT,
        bps INTEGER,
        bonus INTEGER,
        value INTEGER,
        transfers_in INTEGER,
        transfers_out INTEGER,
        PRIMARY KEY (element_id, round)
    );

CREATE TABLE player_past_seasons (
        element_id INTEGER,
        season_name TEXT,
        start_cost INTEGER,
        end_cost INTEGER,
        total_points INTEGER,
        minutes INTEGER,
        goals_scored INTEGER,
        assists INTEGER,
        clean_sheets INTEGER,
        goals_conceded INTEGER,
        bonus INTEGER,
        bps INTEGER,
        influence TEXT,
        creativity TEXT,
        threat TEXT,
        ict_index TEXT,
        PRIMARY KEY (element_id, season_name)
    );

CREATE TABLE fixture_odds_snapshots (
        fixture_id INTEGER,
        event INTEGER,
        home_team TEXT,
        away_team TEXT,
        snapshot_type TEXT, -- 'OPENING' or 'CURRENT'
        home_win_prob REAL,
        draw_prob REAL,
        away_win_prob REAL,
        home_xg REAL,
        away_xg REAL,
        home_cs_prob REAL,
        away_cs_prob REAL,
        recorded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY (fixture_id, snapshot_type)
    );

CREATE TABLE "gw_audit_snapshots" (
                    gw INTEGER,
                    version INTEGER DEFAULT 1,
                    created_at TEXT,
                    updated_at TEXT,
                    status TEXT,
                    chip_played TEXT,
                    formation TEXT,
                    market_weight REAL,
                    factor_movement INTEGER,
                    lineup_json TEXT,
                    transfers_json TEXT,
                    predicted_total REAL,
                    actual_total INTEGER,
                    variance_pts REAL,
                    bench_points INTEGER,
                    captain_id INTEGER,
                    captain_name TEXT,
                    captain_actual_pts INTEGER,
                    vice_captain_id INTEGER,
                    vice_captain_name TEXT,
                    vice_actual_pts INTEGER,
                    PRIMARY KEY (gw, version)
                );

CREATE TABLE "players" (
"can_transact" INTEGER,
  "can_select" INTEGER,
  "chance_of_playing_next_round" REAL,
  "chance_of_playing_this_round" REAL,
  "code" INTEGER,
  "cost_change_event" INTEGER,
  "cost_change_event_fall" INTEGER,
  "cost_change_start" INTEGER,
  "cost_change_start_fall" INTEGER,
  "price_change_percent" TEXT,
  "price_change_hourly_rate" INTEGER,
  "price_change_projections" TEXT,
  "price_change_locked_until" TEXT,
  "price_change_calibrating" INTEGER,
  "dreamteam_count" INTEGER,
  "element_type" INTEGER,
  "ep_next" TEXT,
  "ep_this" TEXT,
  "event_points" INTEGER,
  "first_name" TEXT,
  "form" TEXT,
  "id" INTEGER,
  "in_dreamteam" INTEGER,
  "news" TEXT,
  "news_added" TEXT,
  "now_cost" INTEGER,
  "photo" TEXT,
  "points_per_game" TEXT,
  "removed" INTEGER,
  "second_name" TEXT,
  "selected_by_percent" TEXT,
  "special" INTEGER,
  "squad_number" TEXT,
  "status" TEXT,
  "team" INTEGER,
  "team_code" INTEGER,
  "total_points" INTEGER,
  "transfers_in" INTEGER,
  "transfers_in_event" INTEGER,
  "transfers_out" INTEGER,
  "transfers_out_event" INTEGER,
  "value_form" TEXT,
  "value_season" TEXT,
  "web_name" TEXT,
  "known_name" TEXT,
  "region" REAL,
  "team_join_date" TEXT,
  "birth_date" TEXT,
  "has_temporary_code" INTEGER,
  "opta_code" TEXT,
  "minutes" INTEGER,
  "goals_scored" INTEGER,
  "assists" INTEGER,
  "clean_sheets" INTEGER,
  "goals_conceded" INTEGER,
  "own_goals" INTEGER,
  "penalties_saved" INTEGER,
  "penalties_missed" INTEGER,
  "yellow_cards" INTEGER,
  "red_cards" INTEGER,
  "saves" INTEGER,
  "bonus" INTEGER,
  "bps" INTEGER,
  "influence" TEXT,
  "creativity" TEXT,
  "threat" TEXT,
  "ict_index" TEXT,
  "clearances_blocks_interceptions" INTEGER,
  "recoveries" INTEGER,
  "tackles" INTEGER,
  "defensive_contribution" INTEGER,
  "starts" INTEGER,
  "expected_goals" TEXT,
  "expected_assists" TEXT,
  "expected_goal_involvements" TEXT,
  "expected_goals_conceded" TEXT,
  "corners_and_indirect_freekicks_order" REAL,
  "corners_and_indirect_freekicks_text" TEXT,
  "direct_freekicks_order" REAL,
  "direct_freekicks_text" TEXT,
  "penalties_order" REAL,
  "penalties_text" TEXT,
  "scout_risks" TEXT,
  "scout_news_link" TEXT,
  "influence_rank" INTEGER,
  "influence_rank_type" INTEGER,
  "creativity_rank" INTEGER,
  "creativity_rank_type" INTEGER,
  "threat_rank" INTEGER,
  "threat_rank_type" INTEGER,
  "ict_index_rank" INTEGER,
  "ict_index_rank_type" INTEGER,
  "expected_goals_per_90" REAL,
  "saves_per_90" REAL,
  "expected_assists_per_90" REAL,
  "expected_goal_involvements_per_90" REAL,
  "expected_goals_conceded_per_90" REAL,
  "goals_conceded_per_90" REAL,
  "now_cost_rank" INTEGER,
  "now_cost_rank_type" INTEGER,
  "form_rank" INTEGER,
  "form_rank_type" INTEGER,
  "points_per_game_rank" INTEGER,
  "points_per_game_rank_type" INTEGER,
  "selected_rank" INTEGER,
  "selected_rank_type" INTEGER,
  "starts_per_90" REAL,
  "clean_sheets_per_90" REAL,
  "defensive_contribution_per_90" REAL
);

CREATE TABLE "teams" (
"code" INTEGER,
  "draw" INTEGER,
  "form" TEXT,
  "id" INTEGER,
  "loss" INTEGER,
  "name" TEXT,
  "played" INTEGER,
  "points" INTEGER,
  "position" INTEGER,
  "short_name" TEXT,
  "strength" TEXT,
  "team_division" TEXT,
  "unavailable" INTEGER,
  "win" INTEGER,
  "link_url" TEXT,
  "strength_overall_home" INTEGER,
  "strength_overall_away" INTEGER,
  "strength_attack_home" INTEGER,
  "strength_attack_away" INTEGER,
  "strength_defence_home" INTEGER,
  "strength_defence_away" INTEGER,
  "pulse_id" INTEGER
);

CREATE TABLE "positions" (
"id" INTEGER,
  "plural_name" TEXT,
  "plural_name_short" TEXT,
  "singular_name" TEXT,
  "singular_name_short" TEXT,
  "squad_select" INTEGER,
  "squad_min_select" TEXT,
  "squad_max_select" TEXT,
  "squad_min_play" INTEGER,
  "squad_max_play" INTEGER,
  "ui_shirt_specific" INTEGER,
  "sub_positions_locked" TEXT,
  "element_count" INTEGER
);

CREATE TABLE "events" (
"id" INTEGER,
  "name" TEXT,
  "deadline_time" TEXT,
  "release_time" TEXT,
  "average_entry_score" INTEGER,
  "finished" INTEGER,
  "data_checked" INTEGER,
  "highest_scoring_entry" REAL,
  "deadline_time_epoch" INTEGER,
  "deadline_time_game_offset" INTEGER,
  "highest_score" REAL,
  "is_previous" INTEGER,
  "is_current" INTEGER,
  "is_next" INTEGER,
  "cup_leagues_created" INTEGER,
  "h2h_ko_matches_created" INTEGER,
  "can_enter" INTEGER,
  "can_manage" INTEGER,
  "released" INTEGER,
  "ranked_count" INTEGER,
  "overrides" TEXT,
  "chip_plays" TEXT,
  "most_selected" REAL,
  "most_transferred_in" REAL,
  "top_element" REAL,
  "top_element_info" TEXT,
  "transfers_made" INTEGER,
  "most_captained" REAL,
  "most_vice_captained" REAL
);

CREATE TABLE "fixtures" (
"code" INTEGER,
  "event" INTEGER,
  "finished" INTEGER,
  "finished_provisional" INTEGER,
  "id" INTEGER,
  "kickoff_time" TEXT,
  "minutes" INTEGER,
  "provisional_start_time" INTEGER,
  "started" INTEGER,
  "team_a" INTEGER,
  "team_a_score" REAL,
  "team_h" INTEGER,
  "team_h_score" REAL,
  "stats" TEXT,
  "team_h_difficulty" INTEGER,
  "team_a_difficulty" INTEGER,
  "pulse_id" INTEGER
);